// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/users/user_repositories/user_repository.go
//
// Generated by this command:
//
//	mockgen -source=./internal/users/user_repositories/user_repository.go -destination=mocks/users/user_repositories/user_repository_mock.go -package=userrepositories_mock
//

// Package userrepositories_mock is a generated GoMock package.
package userrepositories_mock

import (
	context "context"
	reflect "reflect"

	userentities "github.com/lunarisnia/crud-example/internal/users/user_entities"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, tx *gorm.DB, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, tx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, tx, name)
}

// ReadAll mocks base method.
func (m *MockUserRepository) ReadAll(ctx context.Context) ([]userentities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", ctx)
	ret0, _ := ret[0].([]userentities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockUserRepositoryMockRecorder) ReadAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockUserRepository)(nil).ReadAll), ctx)
}

// ReadById mocks base method.
func (m *MockUserRepository) ReadById(ctx context.Context, id uint) (userentities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadById", ctx, id)
	ret0, _ := ret[0].(userentities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadById indicates an expected call of ReadById.
func (mr *MockUserRepositoryMockRecorder) ReadById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadById", reflect.TypeOf((*MockUserRepository)(nil).ReadById), ctx, id)
}

// Remove mocks base method.
func (m *MockUserRepository) Remove(ctx context.Context, tx *gorm.DB, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockUserRepositoryMockRecorder) Remove(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockUserRepository)(nil).Remove), ctx, tx, id)
}

// UpdateName mocks base method.
func (m *MockUserRepository) UpdateName(ctx context.Context, tx *gorm.DB, id uint, newName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateName", ctx, tx, id, newName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateName indicates an expected call of UpdateName.
func (mr *MockUserRepositoryMockRecorder) UpdateName(ctx, tx, id, newName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateName", reflect.TypeOf((*MockUserRepository)(nil).UpdateName), ctx, tx, id, newName)
}
